apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeni-proje-backend
  labels:
    app: yeni-proje-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yeni-proje-backend
  template:
    metadata:
      labels:
        app: yeni-proje-backend
    spec:
      containers:
      - name: yeni-proje-backend
        image: kamran7777777/yeni-proje-backend:latest # Ensure the correct image tag
        ports:
        - containerPort: 5000 # Match the port the app is actually listening on
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: yeni-proje-backend-config
              key: PORT
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: yeni-proje-backend-config
              key: CLIENT_URL
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: yeni-proje-backend-config
              key: AWS_REGION
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: yeni-proje-backend-config
              key: S3_BUCKET_NAME
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: JWT_SECRET
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: EMAIL_USER
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: EMAIL_PASS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: PAYPAL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: PAYPAL_CLIENT_ID
        - name: PAYPAL_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: yeni-proje-backend-secrets
              key: PAYPAL_CLIENT_SECRET
